repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
        files: \.(json)$
      - id: check-toml
  - repo: https://github.com/psf/black
    rev: master
    hooks:
      - id: black
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
      - id: flake8
  - repo: https://github.com/timothycrosley/isort
    rev: master
    hooks:
      - id: isort
